name: Australia-vs-India-2024-25-Third-Test-Day-Four

on:
  workflow_dispatch:

jobs:
  Australia-vs-India-2024-25-Third-Test-Day-Four:
    runs-on: ubuntu-latest
    environment: Uploader

    steps:
      - name: Install ffmpeg 
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Download remote bash file
        run: wget ${{ secrets.UPLOADER_URL }}/bash_files/Australia-vs-India-2024-25-Third-Test-Day-Four.sh || echo "Primary URL download failed"

      - name: Install dos2unix
        run: sudo apt install dos2unix -y
          
      - name: Install libavcodec
        run: sudo apt install libavcodec-extra -y

      - name: Install curl
        run: sudo apt install curl -y
        
      - name: Add NodeJS
        run: curl -s https://deb.nodesource.com/setup_18.x | sudo bash
        
      - name: Install NodeJS
        run: sudo apt install nodejs -y
        
      - name: Install Wrangler
        run: npm install wrangler@latest

      - name: Fix issue in downloaded file
        run: sudo dos2unix Australia-vs-India-2024-25-Third-Test-Day-Four.sh
        
      - name: Permission to downloaded file
        run: sudo chmod +x Australia-vs-India-2024-25-Third-Test-Day-Four.sh

      - name: Run the downloaded bash file
        run: sudo bash Australia-vs-India-2024-25-Third-Test-Day-Four.sh
