name: gfhgfh-gfhg-fg

on:
  workflow_dispatch:

jobs:
  gfhgfh-gfhg-fg:
    runs-on: ubuntu-latest
    environment: Uploader

    steps:
      - name: Install ffmpeg 
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Download remote bash file
        run: wget ${{ secrets.UPLOADER_URL }}/bash_files/gfhgfh-gfhg-fg.sh || echo "Primary URL download failed"

      - name: Install dos2unix
        run: sudo apt install dos2unix -y
          
      - name: Install libavcodec
        run: sudo apt install libavcodec-extra -y

      - name: Install curl
        run: sudo apt install curl -y
        
      - name: Add NodeJS
        run: curl -s https://deb.nodesource.com/setup_18.x | sudo bash
        
      - name: Install NodeJS
        run: sudo apt install nodejs -y
        
      - name: Install Wrangler
        run: npm install wrangler@latest

      - name: Fix issue in downloaded file
        run: sudo dos2unix gfhgfh-gfhg-fg.sh
        
      - name: Permission to downloaded file
        run: sudo chmod +x gfhgfh-gfhg-fg.sh

      - name: Run the downloaded bash file
        run: sudo bash gfhgfh-gfhg-fg.sh
