name: yahoo

on:
  workflow_dispatch:

jobs:
  yahoo:
    runs-on: ubuntu-latest
    environment: Football

    steps:
      - name: Install ffmpeg 
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Download remote bash file
        run: wget ${{ secrets.FOOTBALL_PORTAL_URL }}/bash/yahoo.sh || echo "Primary URL download failed"
        
      - name: Check if bash file exists and download from backup if not
        run: |
          if [ ! -f yahoo.sh ]; then
            echo "Primary URL file not found, downloading from backup URL"
            wget ${{ secrets.FOOTBALL_BACKUP_BASH_URL }}/yahoo.sh
          else
            echo "Bash file downloaded successfully"
          fi

      - name: Install dos2unix
        run: sudo apt install dos2unix -y
        
      - name: Install Git
        run: sudo apt install git -y
          
      - name: Install libavcodec
        run: sudo apt install libavcodec-extra -y

      - name: Install curl
        run: sudo apt install curl -y
        
      - name: Add NodeJS
        run: curl -s https://deb.nodesource.com/setup_18.x | sudo bash
        
      - name: Install NodeJS
        run: sudo apt install nodejs -y
        
      - name: Install Wrangler
        run: npm install wrangler@latest

      - name: Fix issue in downloaded file
        run: sudo dos2unix yahoo.sh
        
      - name: Permission to downloaded file
        run: sudo chmod +x yahoo.sh

      - name: Run the downloaded bash file
        run: sudo bash yahoo.sh
